### PR TITLE
feat: add global search

### PR DESCRIPTION
**Pull request by cicciodifranco**
## Overview:
This PR introduces a new feature aimed at enhancing the search capabilities. The primary focus is on enabling users to perform searches using regular expressions (RegExp) across multiple fields

## Changes Made:

- Added a function to parse search queries using regular expressions across specified fields.
- Modified the existing parsing logic to accommodate the new search functionality seamlessly.
- Introduced `MongoQueryOptions` interface to provide users with the flexibility to specify search parameters, including the search key and paths for searching.

### Key Additions:

- `MongoQueryOptions` Interface: Introduced MongoQueryOptions interface to define search parameters, allowing users to specify the search key and paths for searching.
- `getSearch` Function: Implemented a new function getSearch to parse search queries using regular expressions across specified fields. This function enhances the search capability of the library by enabling global searches across multiple fields.

### Result
Users can now pass options to `MongoQuery` decorator (useful for further options like default `limit` or `sort`)
```ts
findAll( MongoQuery({ search: { key: 'q', paths: ['name', 'description'] } }) query: MongoQueryModel)
```
#### Request 
`http://localhost:3000/resources?q=John`
#### Query
```json
{
  "limit": 30,
  "skip": 0,
  "select": {},
  "sort": {},
  "populate": [],
  "filter": {
    "$or": [
      {
        "name": {
          "$regex": "John",
          "$options": "i"
        }
      },
      {
        "description": {
          "$regex": "John",
          "$options": "i"
        }
      }
    ]
  }
}
```

## Impact and Benefits:

- Enhanced Search Capability: Users can now perform more sophisticated searches using regular expressions across multiple fields, improving the overall search experience.
- Improved Flexibility: The addition of the `MongoQueryOptions` interface provides users with greater control over search parameters, enhancing the flexibility of the library.
- Better Usability: With enhanced search capabilities, developers can build applications with more robust search functionality, leading to better usability and user experience.

### CODE REVIEW

**Comment by lucasrochagit** [comment]
@cicciodifranco nice feature, man. I will release it now!

**Review by lucasrochagit — APPROVED** [review]

**Comment by lucasrochagit** [comment]
@cicciodifranco I had an issue when generating the library package due to an error generated by TypeScript when creating a ParameterDecorator, as MongoQueryOptions cannot be nullable:

```shell
TS2322: Type '(...dataOrPipes: (MongoQueryOptions | PipeTransform<any, any> | Type<PipeTransform<any, any>>)[]) => ParameterDecorator' is not assignable to type '(opts?: MongoQueryOptions | undefined) => ParameterDecorator'.   Types of parameters 'dataOrPipes' and 'opts' are incompatible.     Type 'MongoQueryOptions | undefined' is not assignable to type 'MongoQueryOptions | PipeTransform<any, any> | Type<PipeTransform<any, any>>'.       Type 'undefined' is not assignable to type 'MongoQueryOptions | PipeTransform<any, any> | Type<PipeTransform<any, any>>'.
```

Because of this, I will create and expose a method called `MongoQueryOpts`, which performs the same operations as `MongoQuery`, but with the possibility of having search options, as defined in your feature.

If there are questions or new suggestions for implementing this feature, please open a new Pull Request or an Issue, so that I can adjust it.

Thanks for the contribution!

**Comment by cicciodifranco** [comment]
a possible solution could be 
```
export const MongoQuery: (data: MongoQueryOptions | undefined) => ParameterDecorator =
    createParamDecorator(
        (
          data: MongoQueryOptions | undefined,
          ctx: ExecutionContext,
        ): MongoQueryModel => {
          const query = ctx.getArgByIndex(0).query;
          return parse(query, data);
        },
    );
    
```
btw I will open a new pr for that

**Comment by lucasrochagit** [comment]
@cicciodifranco bruh, I didn't considerate this solution 🤦🏻 . No new pr needed, I will fix this now. Thanks!

Edit: feature available on `v.1.0.13` ✅

**Pull request merged**
